name: AspireStarterApp Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/AspireStarterApp"
      - ".github/workflows/aspirestarterapp-test.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src/AspireStarterApp"
      - ".github/workflows/aspirestarterapp-test.yml"

jobs:
  build-and-test:
    uses: ./.github/workflows/shared-test.yml
    with:
      project-name: AspireStarterApp
      solution-path: src/AspireStarterApp/AspireStarterApp.sln
