name: Build and Test a .NET project

on:
  workflow_call:
    inputs:
      project-name:
        description: "The name of the project"
        required: true
        type: string
      solution-path:
        description: "The solution file of the project to build and run tests"
        required: true
        type: string
      dotnet-version:
        description: "The version of .NET to use"
        required: false
        type: string
        default: "8.0.x"
jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Restore NuGet Packages
        run: dotnet restore ${{ inputs.solution-path }}

      # - name: Run unit tests
      #   run: dotnet test --logger trx --results-directory "TestResults-${{ inputs.project-name}}" --no-restore ${{ inputs.solution-path }}

      - name: Run unit tests for matching projects
        shell: bash
        run: |
          # Find test projects matching *.Tests.csproj
          find . -name "*.Tests.csproj" | while read -r testProject; do
            echo "Running tests for $testProject"
            resultsDir="TestResults-${{ inputs.project-name }}/$(basename $testProject .csproj)"
            mkdir -p "$resultsDir"
            dotnet test "$testProject" --logger trx --results-directory "$resultsDir" --no-restore
          done

      - name: Upload the test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ inputs.project-name}}
          path: TestResults-${{ inputs.project-name}}
        if: always()
